### ISSUE TITLE
Is there any way to have the only one engine for all the games?

### ISSUE THREAD

**Issue by myCrack** [ixray-team/ixray-1.6-stcop#11]
It is not a request, but a question. I just want to know what do you think about that.

**Comment by acidicMercury8** [comment]
@myCrack thank you for the question!

At the moment it's impossible to do this at once for several reasons:

- Different versions of dependencies (**LuaJIT**, **Luabind** and etc)
- Different versions of asset formats (levels, spawn and etc)
- Different gameplay features (PDA, faction wars and etc)

But we think about it in perspective

By the way, I have opened discussions for such questions
