### ISSUE TITLE
What makes IX-Ray different from the other projects like OpenXRay?

### ISSUE THREAD

**Issue by myCrack** [ixray-team/ixray-1.6-stcop#12]
Which project goals do you have in mind?

**Comment by myCrack** [comment]
Also, I think you should turn off these Issue templates.

UPD: I found the way how to bypass it.

**Comment by Drombeys** [comment]
The main difference is the approaches to development, attitude towards players and modders. More details will be with the public release, where all documentation, community changelog and FAQ will be available
