### ISSUE TITLE
[РЕШЕНО] «Fatal error occured» только на DX11

### ISSUE THREAD

**Issue by ThIsLinked** [ixray-team/ixray-1.6-stcop#44]
### Description

Кажется, местные из СНГ, да? Тогда буду прямолинейным – эта хрень появляется, если переключиться в улучшенное динамическое DX11.

Скачал ориг. ЗП от Хатаба, установил, ничего больше не делая, запустил. Выбирал любые режимы освещения – работает без проблем. Расширенные настройки графики тоже крутишь – никаких проблем. После каждого изменения в графике перезагружал игру с выгрузкой из памяти (подождал несколько сек. перед запуском + Mem Reduct). То есть в оригинале вообще никаких приколов.

Ставлю [r0.10](https://github.com/ixray-team/ixray-1.6-stcop/releases/tag/r0.10) из ветки. Закидываю в корень со всеми заменами, разумеется. В подтверждение:<details>
<summary>Спойлер</summary>

![1](https://github.com/ixray-team/ixray-1.6-stcop/assets/45180688/f9cc535f-f12c-4dea-a39a-e95d08786236)

</details>
Ничего не трогая, захожу в настройки графики, перевожу освещение в, чтобы не сглазить, «Ул. полное освещение (DX11)», перезапускаю игру и сразу после открытия ярлыком:<details>
<summary>Спойлер</summary>

![2](https://github.com/ixray-team/ixray-1.6-stcop/assets/45180688/7942d880-cc8b-4b54-9de6-3cc5d2f6b565)

</details>
Я что-то не догнал? Причём, проверял статику и полную динамику, любые расширенные настройки – никаких проблем. Только ставишь на ул. полное и сразу эта хрень. У меня есть ещё такие стулкачи: SGM + Gunslinger, SoC Update и CoC. На всех вкл. улучшенное полное DX11 – никаких проблем. Повторюсь, на ЗП без IXRay ул. полное DX11 вертится без проблем. Вот именно на IXRay DX11 такая хрень. DirectX и так далее – ясен пень это всё есть, всё последнее, обновлённое. Что за новые выкрутасы?

### Platform

- B550 AORUS Elite v2
- R7 5700X
- 3600MT CL16 4x16GB
- 1080 Ti AORUS XE 11GB
- Оф. образ Win 11 Pro 22H2 (build 22621.2861, Feature Exp. Pack 1000.22681.1000.0)
- Драйвер Game Ready 552.22 от 16.04.24 (послед. на данный момент)

### Reproduction

Сменить рендер на DX11

### Agreements

- [X] I agree to follow this project's [__Contributing Guidelines__](https://github.com/ixray-team/.github/blob/default/CONTRIBUTING.md)

- [X] I agree to follow this project's [__Code of Conduct__](https://github.com/ixray-team/.github/blob/default/CODE_OF_CONDUCT.md)

**Comment by ForserX** [comment]
Ку, приложи лог

**Comment by Drombeys** [comment]
Только что перепроверил релиз, все работает. Так, прыгни к нам в дискорд будем разбираться https://discord.gg/hWTbHxaYWz

**Comment by ThIsLinked** [comment]
> Ку, приложи лог

Да как раз вспомнил. Значит по порядку, я кое-что нанюхал.

logs-1. Здесь я удалил целиком папку **_appdata_**, зашёл, сменил на ул. полное DX11, перезашёл и словил падение – файл лога и дамп. Взял из " _ appdata _ / logs / ... ".

logs-2. А тут я удалил папку **logs** и **shaders_cache** после смены на ул. полное DX11 – скрыпя зубами можно добраться до кнопки «Новая игра». Бывает, что вылетает сразу после запуска ярлыком. Бывает, что в главном меню. На скринах ошибки сыпятся, когда пытаюсь загрузиться новой игрой.
<details>
<summary>Спойлер</summary>

![3](https://github.com/ixray-team/ixray-1.6-stcop/assets/45180688/1b2126cf-c5cc-4960-92bc-36475069ae2c)

![4](https://github.com/ixray-team/ixray-1.6-stcop/assets/45180688/552d680b-929a-4dca-9669-d9d7c59e4f57)

![5](https://github.com/ixray-team/ixray-1.6-stcop/assets/45180688/a1dd7aac-9d83-4202-9742-d2af3cb5bef5)

</details>
Каждый новый скрин – это нажатие на кнопку "Продолжить" в окне ошибки. После 3-го скрина появляется одна и та же ошибка. На всякий случай делал всё с включенным MSI AB.

_Для справки: До Затона так и не смог добраться._
[logs-1.zip](https://github.com/ixray-team/ixray-1.6-stcop/files/15178439/logs-1.zip)
[logs-2.zip](https://github.com/ixray-team/ixray-1.6-stcop/files/15178441/logs-2.zip)

**Comment by ThIsLinked** [comment]
_Забыл архивы с логами приложить, добавил ^^^_

**Comment by Drombeys** [comment]
Проблема оказалась в луажит, спасибо за фитбек. Скоро заменим на иной вариант
