### ISSUE TITLE
Рандомная перезарядка на оружиях

### ISSUE THREAD

**Issue by Tawelor** [ixray-team/ixray-1.6-stcop#53]
### Please describe if your feature request is related to a problem

Рандомная анимация перезарядки на оружиях. Это хорошо бы вписалось в геймплей игры. Мы все уже привыкаем к однообразным анимациям релоада. 

### Describe the solution you would like

Хотелось бы, чтобы это было просто в конфиге оружия, то есть anm_reload_1 или как-то так. В принципе в ганслингире такое было реализовано на бинтах.

### Describe alternatives you have considered

На некоторых оружиях , таких как ТОЗ или БМ очень легко создать альтернативную анимацию перезарядки. Можно было бы прописать только им в класс

**Comment by Hozar2002** [comment]
Рандомные анимации - оригинальная механика и она всё еще работает.
