### ISSUE TITLE
Не работает комбинация клавиш для низкого присяда

### ISSUE THREAD

**Issue by Revoshell** [ixray-team/ixray-1.6-stcop#55]
### Описание

Доброго времени суток.
Наткнулся на такую проблему.
Обычно я пользуюсь комбинацией клавиш CTRL+LALT для низкого присяда (мне так удобно).
(В игре клавиша левого альта указана как LMENU).
Так вот, при зажатом CTRL (и даже если в настройках включена возможность присесть и не вставать и ты не удерживаешь CTRL) то при последующем нажатии на левый альт персонаж тупо встаёт.

### Платформа

Процессор: Intel Xeon E3-1270
Видеокарта: NVIDIA GeForce GTX 1650 (GDDR5) 4GB
Оперативная память: 24GB (1333 МГЦ)
ОС: Windows 10 Pro (x64) Лицензия
Версия: IX-Ray 1.6 Release 1.0 (Hash: 5de5396ce)

### Воспроизведение

1. Установить клавишу для "присесть": LCONTROL.
2. Установить клавишу для "шаг": LMENU (левый альт).
3. Зажать CTRL (или установить активным параметр постоянного присяда) после чего зажать левый альт.
4. Персонаж не присядет ниже (даже не останется в стандартном присяде) а попросту встанет.

А так же при нажатом левом альте в принципе другие действия не производятся (нет отклика).

**Comment by ForserX** [comment]
Кнопка Alt будет доступна в некст релизе, либо можете поиграть в dev сборки с пайплайнов. В них уже есть исправления по клавишам
