### ISSUE TITLE
Конфиги профилей НПС

### ISSUE THREAD

**Issue by UsalRadja** [ixray-team/ixray-1.6-stcop#56]
### Пожалуйста, опишите, связан ли ваш запрос на добавление новой функции с какой-либо проблемой

Надоело вручную прописывать конкретные числовые значения ранга и репутации в конфигах профилей НПС

### Опишите решение, которое вы хотели бы получить

Возможность генерации числа в заданных пределах аналогично деньгам

**Comment by Drombeys** [comment]
@UsalRadja данная возможность добавлена и будет доступна в следующем релизе 1.1
