### ISSUE TITLE
Название группировки и логотип, ранг и репутация в инвентаре

### ISSUE THREAD

**Issue by PastKNIGHT** [ixray-team/ixray-1.6-stcop#57]
### Пожалуйста, опишите, связан ли ваш запрос на добавление новой функции с какой-либо проблемой

![Снимок](https://github.com/user-attachments/assets/32620159-7ac2-4de9-b275-deeac81eb02c)
Просто в некоторых случаях. От репутации зависит ассортимент торговца. Да и ранг хоть свой наблюдать.

**Comment by Drombeys** [comment]
Данная возможность реализована и влита в основную ветку. Будет доступно в релизе 1.1
