### ISSUE TITLE
Enhance project description

### ISSUE THREAD

**Issue by ChristopherCapito** [ixray-team/ixray-1.6-stcop#64]
### Описание

Greetings!

I have stumbled upon this repository based on a mod/advertisement on moddb (it worked, impeccable strategy lol). Now I am wondering what the "purpose" of this repository/team is as opposed to say:

* OpenXRay
* Anomaly/X-Ray Monolith

Can someone elaborate what the goal of this project is, as opposed to the others? I am mainly asking because, as a long standing stalker fan, I notice that it seems that most people use Anomaly right now. Is this taken into account in terms of features/mod compatibility so players can migrate? Because I am super in favor of having public repositories where people can contribute, as well as the documentation you on the engine / lua you seem to be writing! Very hard resources to come by, especially in english. (Being a dev myself I am trying to understand the source code but its a nightmare haha)

Also: Is there a main communication channel like Discord or some other Chatprogram? Or is all communication centralized in this GitHub repository.

If so, could you add some guides as to where to find e.g. issues/bugs? I noticed some are on the engine repository, but then there is also the general "Tasklist" in the team page.

Thank you for the work and have a good time :) 

### Платформа

-

### Воспроизведение

-

**Comment by Drombeys** [comment]
Hello, @ChristopherCapito! 
All your questions are already answered in our FAQ: https://github.com/ixray-team/ixray-1.6-stcop/blob/default/doc/faq.md
The discord link was written in the repository description :) 
Discord Server: https://discord.gg/hWTbHxaYWz

At the moment, we are focused on our core tasks and integrating platforms such as Soc and CS. There may be compatibility with CoC, but Anomaly mod is not planned to be supported.

Also, we are in the process of translating our platform documentation into other languages

**Comment by ChristopherCapito** [comment]
Thank you for the answer! My bad. I totally didnt see the faq.md :D I was just reading through the toplevel readme links a little. Thanks.
